# Generated by Django 4.0.4 on 2022-07-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0003_alter_location_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='smarticket_api.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='smarticket_api.coordinates'),
        ),
    ]
