# Generated by Django 4.0.4 on 2022-07-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0004_alter_event_location_alter_location_coordinates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
