# Generated by Django 4.0.4 on 2022-07-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0006_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.CharField(max_length=100)),
                ('user_role', models.CharField(choices=[('USER', 'user'), ('STAFF', 'staff'), ('PROMOTER', 'promoter'), ('ADMIN', 'admin')], default='USER', max_length=10)),
                ('wallet_hash', models.CharField(max_length=50)),
            ],
        ),
    ]
