# Generated by Django 4.0.4 on 2022-07-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0007_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
