# Generated by Django 4.0.4 on 2022-07-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0009_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='', max_length=40, primary_key=True, serialize=False),
        ),
    ]
