# Generated by Django 4.0.4 on 2022-08-05 21:46

from django.db import migrations, models
import smarticket_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0012_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to=smarticket_api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
