# Generated by Django 4.0.4 on 2022-08-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0015_rename_category_category_name_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='address2',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
