# Generated by Django 4.0.4 on 2022-08-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0018_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promoter_private_key',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
