# Generated by Django 4.0.4 on 2022-08-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0019_user_promoter_private_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='promoter_private_key',
            new_name='wallet_private_key',
        ),
        migrations.AddField(
            model_name='sale',
            name='txHash',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
