# Generated by Django 4.0.4 on 2022-08-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0020_rename_promoter_private_key_user_wallet_private_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='txHash',
            new_name='purchaseHash',
        ),
        migrations.AddField(
            model_name='sale',
            name='receivedHash',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='refundHash',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
