# Generated by Django 4.0.4 on 2022-08-17 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0021_rename_txhash_sale_purchasehash_sale_receivedhash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 8, 17)),
        ),
    ]
