# Generated by Django 4.0.4 on 2022-08-17 16:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0022_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 16, 25, 28, 726253, tzinfo=utc)),
        ),
    ]
