# Generated by Django 4.0.4 on 2022-08-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0024_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='contractAddress',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
