# Generated by Django 4.0.4 on 2022-08-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0027_alter_contract_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='contractAddress',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='receivedHash',
        ),
        migrations.AddField(
            model_name='sale',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
