# Generated by Django 4.0.4 on 2022-08-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarticket_api', '0028_remove_sale_contractaddress_remove_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
    ]
